name: Go

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'
        check-latest: true

    - name: Get dependencies
      run: |
        go mod tidy
        go mod download

    - name: Run tests
      run: |
        go test -v ./... || exit 1
        echo "Tests completed"

    - name: Run coverage
      run: |
        chmod +x ./scripts/coverage.sh
        ./scripts/coverage.sh || exit 1
        echo "Coverage completed"

    - name: Upload coverage report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: coverage/
        if-no-files-found: error

  benchmark:
    name: Benchmark
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'
        check-latest: true

    - name: Get dependencies
      run: |
        go mod tidy
        go mod download

    - name: Run benchmarks
      run: |
        go test -bench=. -benchmem ./... || exit 1
        echo "Benchmarks completed"

  load-test:
    name: Load Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'
        check-latest: true

    - name: Get dependencies
      run: |
        go mod tidy
        go mod download

    - name: Run load tests
      run: |
        go test -v ./tests/load/... || exit 1
        echo "Load tests completed" 